name: Sync Docker Hub Image to Alibaba Cloud ACR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Alibaba Cloud ACR
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login --username "${{ secrets.ACR_USERNAME }}" registry.cn-hangzhou.aliyuncs.com --password-stdin

    - name: Pull Docker Image from Docker Hub
      run: docker pull docker.io/rancher/fleet-agent:v0.9.5

    - name: Tag Docker Image for Alibaba Cloud ACR
      run: docker tag docker.io/rancher/fleet-agent:v0.9.5 registry.cn-hangzhou.aliyuncs.com/your-acr-namespace/fleet-agent:v0.9.5

    - name: Push Docker Image to Alibaba Cloud ACR
      run: docker push registry.cn-hangzhou.aliyuncs.com/cy828docker/fleet-agent:v0.9.5
